insert into Acquirers (acqID, Name, Sector) values (1, 'Stracke-Schmeler', 'Technology');
insert into Acquirers (acqID, Name, Sector) values (2, 'Parisian Inc', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (3, 'Koss, Borer and Schmitt', 'Technology');
insert into Acquirers (acqID, Name, Sector) values (4, 'Beier-Koepp', 'Technology');
insert into Acquirers (acqID, Name, Sector) values (5, 'Beer Group', 'Retail');
insert into Acquirers (acqID, Name, Sector) values (6, 'Mueller-Donnelly', 'Education');
insert into Acquirers (acqID, Name, Sector) values (7, 'Lubowitz-Lynch', 'Technology');
insert into Acquirers (acqID, Name, Sector) values (8, 'Hammes-Hagenes', 'Technology');
insert into Acquirers (acqID, Name, Sector) values (9, 'Grady and Sons', 'Healthcare');
insert into Acquirers (acqID, Name, Sector) values (10, 'Gleichner, Batz and Schmeler', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (11, 'Bernier Group', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (12, 'Kunde-Aufderhar', 'Technology');
insert into Acquirers (acqID, Name, Sector) values (13, 'Hegmann Inc', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (14, 'Mohr Inc', 'Technology');
insert into Acquirers (acqID, Name, Sector) values (15, 'Konopelski-Lang', 'Healthcare');
insert into Acquirers (acqID, Name, Sector) values (16, 'Doyle, Langosh and Reinger', 'Retail');
insert into Acquirers (acqID, Name, Sector) values (17, 'Purdy Inc', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (18, 'Hahn-Hauck', 'Healthcare');
insert into Acquirers (acqID, Name, Sector) values (19, 'Gutkowski Inc', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (20, 'Lind-Maggio', 'Retail');
insert into Acquirers (acqID, Name, Sector) values (21, 'Rau Inc', 'Technology');
insert into Acquirers (acqID, Name, Sector) values (22, 'Rohan-O''Reilly', 'Technology');
insert into Acquirers (acqID, Name, Sector) values (23, 'Frami-Romaguera', 'Technology');
insert into Acquirers (acqID, Name, Sector) values (24, 'Monahan-Morissette', 'Retail');
insert into Acquirers (acqID, Name, Sector) values (25, 'Bradtke Inc', 'Retail');
insert into Acquirers (acqID, Name, Sector) values (26, 'O''Connell LLC', 'Education');
insert into Acquirers (acqID, Name, Sector) values (27, 'Kuhn-Witting', 'Healthcare');
insert into Acquirers (acqID, Name, Sector) values (28, 'Steuber, Beahan and Lowe', 'Technology');
insert into Acquirers (acqID, Name, Sector) values (29, 'Lemke, Welch and Kerluke', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (30, 'Mann-Schultz', 'Healthcare');
insert into Acquirers (acqID, Name, Sector) values (31, 'MacGyver-Price', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (32, 'Prosacco-Yost', 'Technology');
insert into Acquirers (acqID, Name, Sector) values (33, 'Douglas-Kuvalis', 'Healthcare');
insert into Acquirers (acqID, Name, Sector) values (34, 'Cummerata, Wisozk and Ruecker', 'Retail');
insert into Acquirers (acqID, Name, Sector) values (35, 'Bruen Group', 'Education');
insert into Acquirers (acqID, Name, Sector) values (36, 'Ritchie Group', 'Education');
insert into Acquirers (acqID, Name, Sector) values (37, 'McKenzie-Swift', 'Retail');
insert into Acquirers (acqID, Name, Sector) values (38, 'Stoltenberg-Denesik', 'Education');
insert into Acquirers (acqID, Name, Sector) values (39, 'Macejkovic LLC', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (40, 'Stark Inc', 'Healthcare');
insert into Acquirers (acqID, Name, Sector) values (41, 'Zulauf LLC', 'Retail');
insert into Acquirers (acqID, Name, Sector) values (42, 'Baumbach Inc', 'Education');
insert into Acquirers (acqID, Name, Sector) values (43, 'O''Keefe LLC', 'Education');
insert into Acquirers (acqID, Name, Sector) values (44, 'Schumm-Altenwerth', 'Retail');
insert into Acquirers (acqID, Name, Sector) values (45, 'Bayer-Schmeler', 'Education');
insert into Acquirers (acqID, Name, Sector) values (46, 'Willms, Dicki and Kris', 'Healthcare');
insert into Acquirers (acqID, Name, Sector) values (47, 'Friesen, Hilll and Padberg', 'Technology');
insert into Acquirers (acqID, Name, Sector) values (48, 'Gibson, Sipes and Rath', 'Retail');
insert into Acquirers (acqID, Name, Sector) values (49, 'Deckow-Conn', 'Technology');
insert into Acquirers (acqID, Name, Sector) values (50, 'Goodwin, Hermiston and Schuster', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (51, 'Mayer-Zulauf', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (52, 'Ebert, Lynch and Lockman', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (53, 'Friesen Group', 'Education');
insert into Acquirers (acqID, Name, Sector) values (54, 'Johns, Botsford and Hoeger', 'Healthcare');
insert into Acquirers (acqID, Name, Sector) values (55, 'Miller, Farrell and Lind', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (56, 'Wiegand-Ferry', 'Technology');
insert into Acquirers (acqID, Name, Sector) values (57, 'Reinger LLC', 'Healthcare');
insert into Acquirers (acqID, Name, Sector) values (58, 'Greenholt, Hermann and Williamson', 'Retail');
insert into Acquirers (acqID, Name, Sector) values (59, 'Connelly, Hackett and Zulauf', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (60, 'Kunde-Streich', 'Technology');
insert into Acquirers (acqID, Name, Sector) values (61, 'Hodkiewicz-Stokes', 'Retail');
insert into Acquirers (acqID, Name, Sector) values (62, 'Daniel-Borer', 'Education');
insert into Acquirers (acqID, Name, Sector) values (63, 'Keeling-Nicolas', 'Healthcare');
insert into Acquirers (acqID, Name, Sector) values (64, 'Zulauf-Von', 'Technology');
insert into Acquirers (acqID, Name, Sector) values (65, 'O''Conner-O''Connell', 'Education');
insert into Acquirers (acqID, Name, Sector) values (66, 'Jaskolski and Sons', 'Technology');
insert into Acquirers (acqID, Name, Sector) values (67, 'Erdman, Bashirian and Wyman', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (68, 'Feeney Inc', 'Healthcare');
insert into Acquirers (acqID, Name, Sector) values (69, 'Hills-Schinner', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (70, 'Bradtke, Hammes and Wunsch', 'Retail');
insert into Acquirers (acqID, Name, Sector) values (71, 'Rice and Sons', 'Healthcare');
insert into Acquirers (acqID, Name, Sector) values (72, 'Hudson-Champlin', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (73, 'Kuhn-Mraz', 'Education');
insert into Acquirers (acqID, Name, Sector) values (74, 'Hilll and Sons', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (75, 'McClure, Bernier and Spencer', 'Retail');
insert into Acquirers (acqID, Name, Sector) values (76, 'Fritsch LLC', 'Healthcare');
insert into Acquirers (acqID, Name, Sector) values (77, 'Champlin-Huel', 'Education');
insert into Acquirers (acqID, Name, Sector) values (78, 'Walter-Jones', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (79, 'Treutel, Borer and Kuhic', 'Finance');
insert into Acquirers (acqID, Name, Sector) values (80, 'Ernser Inc', 'Education');