insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (1, 'pending', false, '9/7/2021', '19', '19');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (2, 'rejected', false, '3/12/2021', '76', '46');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (3, 'approved', false, '4/8/2021', '70', '23');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (4, 'pending', false, '7/22/2022', '31', '61');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (5, 'pending', false, '11/2/2022', '56', '28');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (6, 'approved', true, '1/18/2020', '54', '72');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (7, 'approved', true, '9/2/2020', '47', '68');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (8, 'approved', true, '7/12/2023', '21', '56');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (9, 'under evaluation', false, '12/28/2023', '69', '48');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (10, 'pending', false, '4/22/2020', '60', '44');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (11, 'approved', false, '10/12/2020', '6', '34');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (12, 'rejected', false, '6/7/2021', '49', '27');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (13, 'approved', false, '1/20/2024', '50', '74');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (14, 'under evaluation', false, '1/17/2021', '67', '77');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (15, 'under evaluation', true, '3/31/2022', '2', '32');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (16, 'approved', false, '7/10/2021', '34', '62');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (17, 'approved', false, '12/27/2021', '63', '80');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (18, 'under evaluation', false, '5/24/2022', '27', '26');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (19, 'pending', false, '3/26/2020', '11', '21');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (20, 'approved', true, '5/4/2021', '62', '65');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (21, 'rejected', true, '9/19/2020', '79', '38');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (22, 'approved', false, '1/7/2020', '4', '54');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (23, 'under evaluation', false, '10/25/2023', '35', '5');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (24, 'rejected', false, '4/13/2022', '24', '60');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (25, 'pending', true, '6/7/2023', '57', '41');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (26, 'under evaluation', false, '9/18/2020', '32', '40');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (27, 'under evaluation', false, '12/9/2021', '33', '33');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (28, 'pending', true, '5/13/2020', '71', '55');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (29, 'approved', true, '11/9/2020', '12', '4');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (30, 'pending', false, '5/9/2022', '18', '47');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (31, 'rejected', true, '1/29/2023', '7', '31');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (32, 'rejected', false, '11/12/2022', '64', '1');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (33, 'under evaluation', true, '2/16/2021', '66', '13');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (34, 'approved', true, '4/16/2020', '61', '59');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (35, 'pending', false, '11/30/2023', '44', '76');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (36, 'rejected', false, '2/28/2021', '75', '8');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (37, 'approved', true, '7/2/2021', '20', '9');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (38, 'approved', true, '11/11/2021', '37', '37');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (39, 'approved', false, '1/10/2024', '68', '6');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (40, 'pending', false, '6/18/2020', '58', '10');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (41, 'under evaluation', true, '11/6/2022', '40', '18');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (42, 'approved', true, '4/17/2023', '30', '29');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (43, 'under evaluation', false, '3/4/2024', '38', '50');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (44, 'under evaluation', true, '8/15/2021', '59', '11');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (45, 'approved', false, '5/10/2021', '42', '78');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (46, 'approved', false, '1/18/2020', '39', '69');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (47, 'rejected', false, '1/5/2020', '3', '3');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (48, 'approved', true, '9/27/2021', '45', '36');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (49, 'approved', false, '11/7/2021', '46', '7');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (50, 'rejected', true, '9/3/2022', '8', '35');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (51, 'under evaluation', false, '2/15/2022', '1', '43');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (52, 'pending', true, '12/27/2022', '28', '15');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (53, 'rejected', false, '7/25/2020', '41', '16');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (54, 'pending', false, '10/3/2023', '55', '71');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (55, 'pending', false, '11/21/2022', '17', '14');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (56, 'approved', true, '4/8/2022', '29', '63');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (57, 'under evaluation', true, '7/30/2023', '51', '42');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (58, 'under evaluation', false, '9/14/2022', '23', '30');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (59, 'under evaluation', true, '12/5/2020', '5', '66');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (60, 'pending', true, '11/8/2022', '52', '58');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (61, 'approved', true, '7/13/2022', '73', '73');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (62, 'pending', false, '1/3/2024', '48', '49');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (63, 'under evaluation', true, '12/26/2022', '80', '45');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (64, 'rejected', false, '9/11/2023', '10', '64');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (65, 'rejected', true, '5/28/2021', '65', '2');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (66, 'approved', true, '9/23/2023', '78', '79');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (67, 'approved', false, '7/29/2022', '22', '22');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (68, 'under evaluation', true, '6/13/2023', '74', '25');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (69, 'pending', false, '1/21/2023', '9', '12');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (70, 'approved', false, '1/23/2020', '15', '51');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (71, 'approved', true, '7/14/2022', '77', '17');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (72, 'pending', false, '5/9/2022', '72', '24');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (73, 'approved', false, '11/2/2020', '26', '75');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (74, 'rejected', false, '1/24/2022', '16', '39');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (75, 'pending', true, '2/21/2022', '43', '20');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (76, 'rejected', false, '4/12/2020', '36', '57');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (77, 'rejected', true, '3/10/2024', '14', '53');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (78, 'approved', false, '3/20/2021', '53', '70');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (79, 'under evaluation', true, '5/8/2020', '13', '67');
insert into AcquisitionTarget (targetID, status, interested, DateIdentified, StartupID, acqID) values (80, 'pending', true, '1/12/2021', '25', '52');