insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (1, 17, 17, 'approved', false, '11/4/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (2, 78, 15, 'pending', true, '2/10/2023');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (3, 43, 78, 'under evaluation', true, '6/20/2023');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (4, 10, 79, 'approved', false, '2/5/2024');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (5, 16, 39, 'pending', false, '6/26/2020');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (6, 80, 21, 'pending', false, '1/24/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (7, 66, 5 , 'under evaluation', true, '10/1/2023');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (8, 65, 25, 'pending', false, '8/25/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (9, 11, 14, 'rejected', false, '10/8/2023');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (10, 13, 53, 'under evaluation', false, '11/2/2020');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (11, 45, 72, 'under evaluation', false, '6/20/2020');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (12, 12, 9 , 'pending', false, '12/18/2021');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (13, 31, 34, 'approved', true, '1/16/2023');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (14, 56, 66, 'under evaluation', false, '2/28/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (15, 9 , 40, 'approved', true, '3/16/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (16, 37, 18, 'approved', true, '10/25/2020');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (17, 47, 38, 'under evaluation', false, '1/19/2020');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (18, 7 , 11, 'rejected', true, '10/27/2023');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (19, 44, 63, 'under evaluation', false, '3/22/2020');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (20, 41, 75, 'approved', false, '10/25/2023');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (21, 3 , 35, 'under evaluation', true, '6/6/2021');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (22, 32, 48, 'under evaluation', false, '2/19/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (23, 74, 8 , 'pending', false, '9/20/2023');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (24, 19, 50, 'approved', false, '11/17/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (25, 64, 57, 'pending', false, '5/3/2023');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (26, 71, 7 , 'approved', false, '7/8/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (27, 2 , 51, 'rejected', false, '12/3/2021');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (28, 68, 59, 'under evaluation', false, '10/10/2023');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (29, 39, 70, 'rejected', true, '5/20/2023');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (30, 14, 80, 'rejected', true, '10/5/2021');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (31, 54, 20, 'under evaluation', true, '5/27/2020');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (32, 8 , 61, 'approved', true, '5/28/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (33, 30, 19, 'approved', false, '12/5/2021');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (34, 46, 49, 'rejected', false, '6/13/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (35, 5 , 58, 'under evaluation', false, '4/11/2020');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (36, 4 , 28, 'rejected', true, '11/1/2020');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (37, 79, 32, 'approved', false, '4/3/2024');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (38, 61, 71, 'rejected', false, '11/9/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (39, 73, 3 , 'under evaluation', false, '7/30/2020');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (40, 52, 16, 'under evaluation', false, '8/18/2021');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (41, 25, 4 , 'approved', true, '3/26/2020');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (42, 34, 12, 'approved', true, '12/21/2020');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (43, 60, 77, 'rejected', true, '9/27/2021');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (44, 23, 47, 'pending', false, '3/20/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (45, 38, 30, 'approved', true, '4/7/2020');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (46, 48, 73, 'approved', true, '12/17/2021');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (47, 26, 29, 'under evaluation', false, '11/2/2023');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (48, 35, 64, 'pending', true, '10/5/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (49, 72, 33, 'under evaluation', false, '7/2/2023');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (50, 40, 2 , 'approved', false, '11/14/2020');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (51, 29, 56, 'approved', false, '7/8/2021');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (52, 18, 68, 'pending', false, '7/16/2020');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (53, 1 , 60, 'pending', false, '1/23/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (54, 28, 6 , 'rejected', true, '3/20/2021');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (55, 70, 10, 'pending', false, '2/6/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (56, 63, 54, 'rejected', false, '3/24/2024');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (57, 75, 46, 'approved', true, '2/12/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (58, 21, 13, 'approved', true, '4/3/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (59, 6 , 37, 'rejected', false, '11/25/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (60, 53, 41, 'under evaluation', false, '5/9/2021');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (61, 42, 1 , 'under evaluation', true, '6/20/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (62, 24, 69, 'approved', true, '9/3/2023');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (63, 57, 24, 'pending', true, '12/11/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (64, 27, 36, 'pending', false, '11/26/2023');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (65, 49, 22, 'under evaluation', true, '9/17/2021');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (66, 50, 76, 'pending', false, '11/7/2023');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (67, 20, 74, 'under evaluation', false, '11/1/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (68, 62, 31, 'rejected', false, '6/24/2020');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (69, 67, 27, 'approved', false, '8/1/2021');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (70, 77, 67, 'under evaluation', false, '9/11/2021');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (71, 22, 55, 'under evaluation', true, '1/2/2024');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (72, 36, 52, 'under evaluation', true, '1/7/2022');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (73, 33, 42, 'rejected', true, '2/15/2023');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (74, 69, 45, 'approved', false, '5/16/2021');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (75, 51, 62, 'rejected', false, '7/9/2020');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (76, 15, 26, 'rejected', true, '6/6/2020');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (77, 55, 65, 'rejected', true, '11/18/2020');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (78, 59, 23, 'pending', true, '1/2/2024');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (79, 58, 43, 'rejected', true, '11/16/2023');
insert into AcquisitionTarget (targetID, StartupID, acqID, status, interested, DateIdentified) values (80, 76, 44, 'approved', false, '3/17/2021');