insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (1, 'current ratio', 0.04, '15');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (2, 'current ratio', 0.21, '56');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (3, 'debt-to-equity ratio', 0.11, '39');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (4, 'gross profit margin', 0.51, '20');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (5, 'debt-to-equity ratio', 0.91, '21');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (6, 'return on assets', 0.98, '32');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (7, 'debt-to-equity ratio', 0.31, '78');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (8, 'return on assets', 0.71, '19');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (9, 'debt-to-equity ratio', 0.53, '71');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (10, 'return on assets', 0.22, '9');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (11, 'return on assets', 0.57, '57');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (12, 'return on assets', 0.17, '14');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (13, 'gross profit margin', 0.08, '61');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (14, 'current ratio', 0.2, '68');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (15, 'current ratio', 0.72, '13');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (16, 'return on assets', 0.83, '53');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (17, 'return on assets', 0.19, '26');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (18, 'current ratio', 0.86, '28');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (19, 'return on assets', 0.28, '58');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (20, 'current ratio', 0.69, '41');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (21, 'debt-to-equity ratio', 0.17, '29');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (22, 'return on assets', 0.13, '8');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (23, 'debt-to-equity ratio', 0.73, '60');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (24, 'current ratio', 0.88, '38');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (25, 'return on assets', 0.34, '3');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (26, 'current ratio', 0.55, '76');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (27, 'return on assets', 0.98, '44');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (28, 'current ratio', 0.33, '4');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (29, 'gross profit margin', 0.06, '2');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (30, 'current ratio', 0.8, '34');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (31, 'return on assets', 0.04, '46');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (32, 'gross profit margin', 0.64, '67');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (33, 'return on assets', 0.01, '74');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (34, 'current ratio', 0.75, '43');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (35, 'return on assets', 0.56, '7');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (36, 'return on assets', 0.42, '50');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (37, 'debt-to-equity ratio', 0.44, '37');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (38, 'gross profit margin', 0.6, '45');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (39, 'gross profit margin', 0.36, '1');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (40, 'return on assets', 0.4, '72');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (41, 'gross profit margin', 0.15, '16');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (42, 'current ratio', 0.0, '22');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (43, 'return on assets', 0.78, '10');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (44, 'debt-to-equity ratio', 0.75, '69');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (45, 'current ratio', 0.85, '23');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (46, 'debt-to-equity ratio', 0.33, '65');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (47, 'gross profit margin', 0.55, '80');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (48, 'return on assets', 0.75, '18');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (49, 'return on assets', 0.05, '36');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (50, 'current ratio', 0.96, '12');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (51, 'gross profit margin', 0.45, '63');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (52, 'debt-to-equity ratio', 0.89, '33');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (53, 'current ratio', 0.65, '25');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (54, 'current ratio', 0.03, '48');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (55, 'gross profit margin', 0.44, '6');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (56, 'debt-to-equity ratio', 0.39, '73');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (57, 'return on assets', 0.91, '51');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (58, 'debt-to-equity ratio', 0.47, '42');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (59, 'return on assets', 0.72, '49');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (60, 'debt-to-equity ratio', 0.71, '59');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (61, 'return on assets', 0.8, '17');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (62, 'debt-to-equity ratio', 0.97, '31');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (63, 'current ratio', 0.56, '62');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (64, 'return on assets', 0.25, '30');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (65, 'current ratio', 0.24, '64');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (66, 'current ratio', 0.79, '55');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (67, 'return on assets', 0.61, '40');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (68, 'gross profit margin', 0.42, '5');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (69, 'gross profit margin', 0.74, '47');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (70, 'current ratio', 0.67, '79');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (71, 'gross profit margin', 0.85, '54');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (72, 'return on assets', 0.5, '66');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (73, 'current ratio', 0.62, '24');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (74, 'return on assets', 0.98, '35');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (75, 'debt-to-equity ratio', 0.59, '52');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (76, 'gross profit margin', 0.3, '70');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (77, 'debt-to-equity ratio', 0.74, '77');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (78, 'return on assets', 0.42, '11');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (79, 'gross profit margin', 0.06, '27');
insert into FinancialMetrics (MetricID, MetricTitle, MetricValue, StartupID) values (80, 'current ratio', 0.12, '75');