insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (1, 15, 'return on assets', 2123.39);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (2, 68, 'debt-to-equity ratio', 1671.89);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (3, 43, 'return on assets', 6203.9);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (4, 32, 'profit margin', 9426.39);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (5, 2 , 'return on assets', 2604.97);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (6, 17, 'debt-to-equity ratio', 5741.37);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (7, 30, 'return on assets', 4954.16);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (8, 16, 'earnings per share', 7774.75);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (9, 9 , 'earnings per share', 4944.58);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (10, 34, 'earnings per share', 4142.69);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (11, 80, 'profit margin', 2058.2);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (12, 53, 'earnings per share', 3389.25);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (13, 66, 'earnings per share', 3095.31);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (14, 71, 'return on assets', 4415.38);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (15, 45, 'return on assets', 1256.42);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (16, 64, 'earnings per share', 2013.18);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (17, 75, 'earnings per share', 3271.49);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (18, 8 , 'debt-to-equity ratio', 9342.77);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (19, 25, 'debt-to-equity ratio', 8248.2);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (20, 72, 'earnings per share', 1925.17);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (21, 21, 'profit margin', 3409.43);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (22, 62, 'debt-to-equity ratio', 2625.62);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (23, 44, 'profit margin', 7602.47);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (24, 33, 'return on assets', 816.75);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (25, 46, 'return on assets', 5571.18);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (26, 41, 'debt-to-equity ratio', 6762.17);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (27, 20, 'debt-to-equity ratio', 5789.28);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (28, 56, 'return on assets', 1758.3);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (29, 35, 'earnings per share', 3635.58);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (30, 67, 'debt-to-equity ratio', 7350.4);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (31, 65, 'return on assets', 6563.99);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (32, 3 , 'return on assets', 6816.0);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (33, 31, 'return on assets', 8542.9);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (34, 29, 'earnings per share', 1932.27);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (35, 57, 'return on assets', 689.1);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (36, 28, 'return on assets', 3506.55);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (37, 19, 'profit margin', 9163.25);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (38, 36, 'debt-to-equity ratio', 5730.25);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (39, 13, 'debt-to-equity ratio', 5438.77);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (40, 27, 'earnings per share', 3127.99);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (41, 61, 'debt-to-equity ratio', 564.6);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (42, 11, 'earnings per share', 5885.21);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (43, 38, 'debt-to-equity ratio', 1611.25);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (44, 39, 'debt-to-equity ratio', 9243.5);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (45, 78, 'profit margin', 9487.09);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (46, 74, 'return on assets', 7303.72);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (47, 47, 'return on assets', 8507.19);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (48, 69, 'return on assets', 7848.48);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (49, 6 , 'profit margin', 2513.78);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (50, 14, 'profit margin', 2991.14);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (51, 24, 'debt-to-equity ratio', 1485.98);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (52, 23, 'profit margin', 5439.6);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (53, 49, 'earnings per share', 9881.49);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (54, 73, 'earnings per share', 4363.37);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (55, 51, 'debt-to-equity ratio', 1394.16);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (56, 42, 'return on assets', 7268.94);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (57, 70, 'return on assets', 9880.09);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (58, 50, 'earnings per share', 9943.42);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (59, 4 , 'debt-to-equity ratio', 1926.7);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (60, 58, 'return on assets', 5955.15);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (61, 60, 'profit margin', 2497.9);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (62, 26, 'debt-to-equity ratio', 8545.05);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (63, 37, 'profit margin', 9055.84);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (64, 79, 'debt-to-equity ratio', 654.21);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (65, 10, 'profit margin', 8461.56);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (66, 54, 'debt-to-equity ratio', 1421.73);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (67, 52, 'return on assets', 8517.76);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (68, 55, 'debt-to-equity ratio', 3664.31);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (69, 76, 'debt-to-equity ratio', 8694.19);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (70, 1 , 'debt-to-equity ratio', 1575.95);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (71, 48, 'profit margin', 4605.95);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (72, 5 , 'return on assets', 5555.09);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (73, 18, 'return on assets', 6322.44);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (74, 12, 'return on assets', 2620.5);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (75, 77, 'earnings per share', 4804.16);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (76, 63, 'return on assets', 6972.17);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (77, 40, 'return on assets', 5124.11);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (78, 7 , 'earnings per share', 8378.93);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (79, 59, 'profit margin', 7978.99);
insert into FinancialMetrics (MetricID, StartupID, MetricTitle, MetricValue) values (80, 22, 'return on assets', 6193.9);