insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (1, 'Hannam University', 'Wolfy McCauley', 'Teaching', 'Mathematics');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (2, 'Washington College', 'Cello Lewis', 'Publication', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (3, 'University College London, University of London', 'Huey Plewman', 'Research', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (4, 'Universidade do Oeste Paulista', 'Urbano Blackburn', 'Teaching', 'Mathematics');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (5, 'Shih Chien University', 'Laurens Rupert', 'Research', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (6, 'Jönköping University College', 'Quintus Guidoni', 'Teaching', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (7, 'Xijiang University', 'Fleurette Gravell', 'Publication', 'Mathematics');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (8, 'Université Kongo', 'Errol Sandell', 'Teaching', 'Science');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (9, 'Central University of Finance and Economics', 'Dara Boulter', 'Research', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (10, 'Turkish Military Academy', 'Grenville Lightfoot', 'Publication', 'Science');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (11, 'National Hualien Teachers College', 'Deina Charrington', 'Teaching', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (12, 'Erskine College', 'Corabella Sprules', 'Teaching', 'Mathematics');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (13, 'Universidad Nacional', 'Germayne Denison', 'Research', 'Science');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (14, 'Kabardino-Balkarian State University', 'Cheston Emig', 'Teaching', 'Science');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (15, 'Central Institute of Higher Tibetan Studies', 'Ario Winfield', 'Publication', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (16, 'St. George''s University', 'Madonna Morgans', 'Research', 'Mathematics');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (17, 'Kumamoto Prefectural University', 'Gabbie Vedstra', 'Teaching', 'Mathematics');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (18, 'Kazakh British Technical University', 'Chere Maysor', 'Research', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (19, 'Tyumen State Agricultural Academy', 'Ryann Baudinet', 'Publication', 'Mathematics');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (20, 'Université Libre de Bruxelles', 'Annabelle Fenich', 'Teaching', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (21, 'Targu-Mures University of Theatre', 'Garwood Ingray', 'Research', 'Science');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (22, 'International College', 'Isabelle Tethcote', 'Publication', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (23, 'University of Regina Carmeli', 'Dido Luetchford', 'Research', 'Mathematics');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (24, 'Tambov State Technical University', 'Ben Preddy', 'Research', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (25, 'Union Theological Seminary (UTS)', 'Glori Skryne', 'Research', 'Mathematics');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (26, 'Islamic Azad University, North Tehran', 'Frazer Stebbin', 'Research', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (27, 'Royal University of Agriculture', 'Benji Downing', 'Teaching', 'Mathematics');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (28, 'Atlantic International University', 'Cinderella Pickrell', 'Research', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (29, 'Columbia Southern University', 'Tiena O''Collopy', 'Teaching', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (30, 'City University', 'Grenville Scarsbrick', 'Research', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (31, 'University of Aquila', 'Corrie Deneve', 'Teaching', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (32, 'Neelain University', 'Bartel McGloin', 'Publication', 'Mathematics');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (33, 'Curry College', 'Meryl Bullingham', 'Research', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (34, 'Centro Universitário Newton Paiva', 'Berta Eagan', 'Research', 'Science');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (35, 'Wayo Women''s University', 'Deana Damiral', 'Publication', 'Science');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (36, 'Ecole Nationale Supérieure d''Electrochimie et d''Electrométallurgie de Gernoble', 'Magdaia Obin', 'Publication', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (37, 'Shahrood University of Medical Sciences', 'Jeannie Barrett', 'Teaching', 'Mathematics');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (38, 'University of Glasgow', 'Ginni Bilbery', 'Publication', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (39, 'Donau-Universität Krems', 'Noe Lethieulier', 'Research', 'Science');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (40, 'Millsaps College', 'Cad Caig', 'Publication', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (41, 'National Taipei Teachers College', 'Bev Hurford', 'Research', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (42, 'Universidad Estatal a Distancia', 'Karalee Couves', 'Publication', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (43, 'Sungshin Women''s University', 'Doria Dedam', 'Publication', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (44, 'Universidad Salesiana', 'Dannie Nuschke', 'Publication', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (45, 'Kazan State Finance and Economics Institute ', 'Sarina Butt', 'Teaching', 'Science');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (46, 'Al-Batterjee Medical College', 'Ruby Ronaldson', 'Teaching', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (47, 'Fuji University', 'Frazier Wiltshire', 'Teaching', 'Science');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (48, 'Fundación Universitaria San Martín', 'Whittaker Muncie', 'Publication', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (49, 'Rocky Mountain College of Art and Design', 'Brittne Widdowson', 'Publication', 'Mathematics');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (50, 'Kazan State University of Medicine', 'Peggie Matterson', 'Publication', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (51, 'Hochschule für Technik und Wirtschaft Karlsruhe', 'Maryanne Dormer', 'Publication', 'Mathematics');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (52, 'Sultan Haji Ahmad Shah Polytechnic', 'Ines Davidy', 'Publication', 'Science');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (53, 'Universidade Luterana do Brasil', 'Tremaine Trowill', 'Teaching', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (54, 'Barat College', 'Fidelity Chidley', 'Research', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (55, 'Samara State Aerospace University', 'Felisha Mughal', 'Publication', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (56, 'Kasem Bundit University', 'Carver Rosenfelder', 'Publication', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (57, 'Kaohsiung Medical College', 'Bail Penson', 'Publication', 'Science');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (58, 'Kyrgyz Turkish  Manas University', 'Grantham Caveney', 'Teaching', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (59, 'Technological University (Sittwe)', 'Odo Jery', 'Teaching', 'Mathematics');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (60, 'Iwate Prefectural University', 'Karlen Malan', 'Publication', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (61, 'University of Tuzla', 'Denys Cupitt', 'Research', 'Science');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (62, 'Asia Europe University', 'Charlotte Klimowski', 'Teaching', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (63, 'Trinity College Connecticut', 'Tandie Farquharson', 'Publication', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (64, 'Guru Jambeshwar University', 'Mirabel Bremen', 'Research', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (65, 'Centre Universitaire de Technologie', 'Henry Crosio', 'Teaching', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (66, 'Ohio State University - Marion', 'Tamera Spada', 'Teaching', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (67, 'Tamil Nadu Dr. Ambedkar Law University', 'Lorain Buck', 'Publication', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (68, 'Osaka University of Economics', 'Arv Pancast', 'Teaching', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (69, 'Portland State University', 'Morgan Cancott', 'Teaching', 'Science');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (70, 'Meiji Gakuin University', 'Jill Pimmocke', 'Research', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (71, 'Singapore Management University', 'Nikolaos Jerisch', 'Teaching', 'Mathematics');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (72, 'Chongqing Telecommunication College', 'Lisa Whacket', 'Publication', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (73, 'Aria Institute of Higher Education', 'Cornelia Daughtery', 'Publication', 'Technology');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (74, 'Guangzhou Normal University', 'Andy Tourle', 'Research', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (75, 'Daido Institute of Technology', 'Talya Barosch', 'Research', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (76, 'Omsk State University', 'Obie Matyja', 'Teaching', 'Mathematics');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (77, 'University Oil- Gas Ploiesti', 'Loralyn Carillo', 'Publication', 'Mathematics');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (78, 'Jeonju University', 'Mandel Frodsam', 'Publication', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (79, 'Vinayaka Mission''s Research Foundation-Deemed University', 'Bren Bletso', 'Research', 'Engineering');
insert into GeneralResearcher (researcherID, University, Name, Interests, FieldOfStudy) values (80, 'Lakshmibai National Institute of Physical Education', 'Worth Marriott', 'Teaching', 'Mathematics');