insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (78, 78, '12/12/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (52, 74, '5/2/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (30, 57, '6/10/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (29, 72, '7/27/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (22, 60, '9/1/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (13, 54, '11/11/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (12, 16, '3/16/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (70, 8 , '3/9/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (26, 5 , '4/21/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (6 , 58, '9/22/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) valuAes (5 , 44, '8/18/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (40, 77, '3/14/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (68, 31, '7/17/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (23, 11, '2/2/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (63, 36, '2/3/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (14, 1 , '3/5/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (62, 56, '12/13/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (59, 49, '12/5/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (28, 22, '5/14/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (56, 53, '12/16/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (72, 30, '6/29/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (45, 64, '11/6/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (43, 2 , '8/25/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (39, 73, '9/5/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (50, 76, '10/28/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (32, 19, '6/22/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (69, 4 , '5/1/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (42, 10, '12/21/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (33, 27, '9/7/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (21, 14, '3/23/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (16, 65, '3/5/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (2 , 75, '1/28/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (58, 37, '9/12/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (24, 69, '12/14/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (49, 9 , '10/11/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (34, 25, '3/29/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (54, 62, '2/26/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (46, 32, '2/2/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (53, 48, '7/30/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (19, 18, '3/5/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (27, 20, '3/17/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (66, 21, '3/4/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (64, 6 , '3/12/2024');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (48, 43, '4/17/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (37, 68, '1/12/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (31, 80, '1/29/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (80, 29, '3/31/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (61, 52, '5/25/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (41, 67, '2/6/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (7 , 46, '11/27/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (8 , 50, '4/29/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (44, 34, '1/21/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (3 , 70, '1/4/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (51, 55, '4/4/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (65, 28, '2/23/2024');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (60, 71, '1/11/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (4 , 51, '3/23/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (36, 7 , '12/16/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (74, 42, '6/7/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (79, 79, '11/19/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (57, 3 , '1/30/2024');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (20, 15, '3/4/2024');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (10, 13, '9/30/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (15, 17, '10/13/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (11, 40, '9/3/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (67, 66, '10/24/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (73, 38, '3/30/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (25, 23, '12/30/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (9 , 33, '11/2/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (18, 47, '2/26/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (38, 24, '10/2/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (76, 26, '11/27/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (77, 35, '9/7/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (17, 39, '9/11/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (47, 12, '5/14/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (35, 59, '4/18/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (55, 41, '7/17/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (71, 63, '8/15/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (1 , 61, '1/10/2024');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (75, 45, '9/1/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (72, 15, '2/3/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (22, 77, '6/29/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (43, 50, '8/13/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (56, 79, '6/22/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (13, 70, '4/24/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (74, 2 , '2/24/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (40, 64, '10/11/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (62, 33, '2/24/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (42, 24, '4/27/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (76, 13, '7/16/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (29, 58, '8/2/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (52, 44, '3/12/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (70, 21, '1/6/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (35, 36, '2/15/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (33, 60, '7/18/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (49, 73, '4/5/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (60, 4 , '6/4/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (69, 51, '8/6/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (18, 38, '2/17/2024');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (39, 34, '3/13/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (32, 53, '3/12/2024');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (38, 9 , '8/8/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (68, 20, '3/13/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (1 , 11, '11/23/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (25, 35, '3/18/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (57, 69, '4/17/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (45, 40, '10/27/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (77, 59, '8/12/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (24, 61, '9/18/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (2 , 5 , '5/29/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (58, 54, '2/22/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (27, 28, '5/27/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (12, 27, '4/12/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (14, 80, '6/27/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (75, 45, '8/19/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (54, 76, '6/21/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (31, 6 , '7/31/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (23, 31, '10/25/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (15, 72, '4/2/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (30, 10, '5/28/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (8 , 78, '5/27/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (36, 7 , '11/11/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (10, 8 , '1/13/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (67, 43, '1/17/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (11, 65, '11/23/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (78, 47, '3/13/2024');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (28, 12, '1/1/2024');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (5 , 22, '6/19/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (6 , 16, '4/26/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (55, 26, '6/8/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (71, 66, '8/6/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (26, 17, '12/11/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (53, 39, '4/26/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (51, 25, '10/6/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (16, 42, '3/19/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (4 , 67, '9/4/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (3 , 74, '8/19/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (63, 19, '12/28/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (66, 1 , '11/29/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (48, 55, '9/7/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (50, 52, '6/26/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (46, 29, '12/5/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (21, 71, '6/23/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (9 , 48, '8/6/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (44, 41, '5/11/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (34, 37, '10/12/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (73, 49, '1/1/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (37, 18, '10/7/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (61, 68, '4/7/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (64, 30, '10/1/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (59, 63, '10/16/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (7 , 62, '3/5/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (41, 57, '5/24/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (17, 3 , '5/11/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (19, 32, '9/6/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (80, 56, '8/24/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (65, 75, '10/7/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (79, 46, '2/6/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (47, 14, '10/8/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (44, 23, '1/27/2024');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (59, 68, '3/10/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (57, 77, '7/8/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (7 , 15, '7/11/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (60, 30, '10/23/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (36, 52, '9/28/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (54, 11, '1/17/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (39, 49, '8/15/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (68, 26, '12/6/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (73, 60, '5/12/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (72, 36, '9/28/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (51, 3 , '7/24/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (34, 35, '11/29/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (48, 20, '12/20/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (42, 79, '7/31/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (5 , 42, '4/1/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (80, 6 , '9/30/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (74, 57, '7/15/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (17, 41, '9/8/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (61, 7 , '5/3/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (10, 16, '11/18/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (49, 1 , '2/8/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (37, 46, '6/22/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (76, 55, '12/26/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (2 , 33, '10/14/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (47, 50, '3/24/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (21, 8 , '12/12/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (41, 43, '9/22/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (1 , 63, '3/10/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (64, 44, '2/21/2024');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (3 , 21, '11/21/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (23, 80, '12/2/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (77, 58, '8/26/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (19, 22, '5/11/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (66, 25, '3/6/2024');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (40, 4 , '3/29/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (78, 12, '8/14/2021');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (56, 37, '3/24/2022');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (31, 64, '3/28/2020');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (52, 23, '4/9/2023');
insert into GeneralResearcherFollowing (researcherID, StartupID, DateCreated) values (18, 76, '5/24/2021');
