insert into InvestmentOpportunityToVC (VCID, OppID) values (36, 30);
insert into InvestmentOpportunityToVC (VCID, OppID) values (50, 32);
insert into InvestmentOpportunityToVC (VCID, OppID) values (10, 8 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (6 , 36);
insert into InvestmentOpportunityToVC (VCID, OppID) values (48, 1 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (57, 59);
insert into InvestmentOpportunityToVC (VCID, OppID) values (4 , 37);
insert into InvestmentOpportunityToVC (VCID, OppID) values (49, 13);
insert into InvestmentOpportunityToVC (VCID, OppID) values (16, 53);
insert into InvestmentOpportunityToVC (VCID, OppID) values (52, 69);
insert into InvestmentOpportunityToVC (VCID, OppID) values (74, 18);
insert into InvestmentOpportunityToVC (VCID, OppID) values (77, 38);
insert into InvestmentOpportunityToVC (VCID, OppID) values (39, 52);
insert into InvestmentOpportunityToVC (VCID, OppID) values (43, 43);
insert into InvestmentOpportunityToVC (VCID, OppID) values (60, 55);
insert into InvestmentOpportunityToVC (VCID, OppID) values (17, 3 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (44, 48);
insert into InvestmentOpportunityToVC (VCID, OppID) values (37, 54);
insert into InvestmentOpportunityToVC (VCID, OppID) values (42, 26);
insert into InvestmentOpportunityToVC (VCID, OppID) values (65, 57);
insert into InvestmentOpportunityToVC (VCID, OppID) values (28, 64);
insert into InvestmentOpportunityToVC (VCID, OppID) values (51, 71);
insert into InvestmentOpportunityToVC (VCID, OppID) values (75, 67);
insert into InvestmentOpportunityToVC (VCID, OppID) values (45, 15);
insert into InvestmentOpportunityToVC (VCID, OppID) values (40, 63);
insert into InvestmentOpportunityToVC (VCID, OppID) values (21, 27);
insert into InvestmentOpportunityToVC (VCID, OppID) values (29, 44);
insert into InvestmentOpportunityToVC (VCID, OppID) values (73, 14);
insert into InvestmentOpportunityToVC (VCID, OppID) values (27, 2 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (62, 74);
insert into InvestmentOpportunityToVC (VCID, OppID) values (3 , 19);
insert into InvestmentOpportunityToVC (VCID, OppID) values (25, 31);
insert into InvestmentOpportunityToVC (VCID, OppID) values (55, 35);
insert into InvestmentOpportunityToVC (VCID, OppID) values (1 , 28);
insert into InvestmentOpportunityToVC (VCID, OppID) values (35, 80);
insert into InvestmentOpportunityToVC (VCID, OppID) values (46, 39);
insert into InvestmentOpportunityToVC (VCID, OppID) values (13, 4 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (71, 22);
insert into InvestmentOpportunityToVC (VCID, OppID) values (7 , 9 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (26, 75);
insert into InvestmentOpportunityToVC (VCID, OppID) values (64, 16);
insert into InvestmentOpportunityToVC (VCID, OppID) values (12, 12);
insert into InvestmentOpportunityToVC (VCID, OppID) values (53, 79);
insert into InvestmentOpportunityToVC (VCID, OppID) values (79, 51);
insert into InvestmentOpportunityToVC (VCID, OppID) values (58, 47);
insert into InvestmentOpportunityToVC (VCID, OppID) values (2 , 60);
insert into InvestmentOpportunityToVC (VCID, OppID) values (14, 56);
insert into InvestmentOpportunityToVC (VCID, OppID) values (72, 77);
insert into InvestmentOpportunityToVC (VCID, OppID) values (70, 76);
insert into InvestmentOpportunityToVC (VCID, OppID) values (23, 29);
insert into InvestmentOpportunityToVC (VCID, OppID) values (15, 5 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (47, 33);
insert into InvestmentOpportunityToVC (VCID, OppID) values (80, 42);
insert into InvestmentOpportunityToVC (VCID, OppID) values (41, 50);
insert into InvestmentOpportunityToVC (VCID, OppID) values (66, 58);
insert into InvestmentOpportunityToVC (VCID, OppID) values (5 , 21);
insert into InvestmentOpportunityToVC (VCID, OppID) values (34, 6 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (24, 49);
insert into InvestmentOpportunityToVC (VCID, OppID) values (76, 10);
insert into InvestmentOpportunityToVC (VCID, OppID) values (20, 23);
insert into InvestmentOpportunityToVC (VCID, OppID) values (30, 17);
insert into InvestmentOpportunityToVC (VCID, OppID) values (19, 40);
insert into InvestmentOpportunityToVC (VCID, OppID) values (68, 68);
insert into InvestmentOpportunityToVC (VCID, OppID) values (32, 61);
insert into InvestmentOpportunityToVC (VCID, OppID) values (69, 65);
insert into InvestmentOpportunityToVC (VCID, OppID) values (11, 45);
insert into InvestmentOpportunityToVC (VCID, OppID) values (33, 24);
insert into InvestmentOpportunityToVC (VCID, OppID) values (8 , 25);
insert into InvestmentOpportunityToVC (VCID, OppID) values (31, 66);
insert into InvestmentOpportunityToVC (VCID, OppID) values (63, 78);
insert into InvestmentOpportunityToVC (VCID, OppID) values (61, 34);
insert into InvestmentOpportunityToVC (VCID, OppID) values (78, 46);
insert into InvestmentOpportunityToVC (VCID, OppID) values (54, 70);
insert into InvestmentOpportunityToVC (VCID, OppID) values (9 , 41);
insert into InvestmentOpportunityToVC (VCID, OppID) values (56, 7 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (67, 62);
insert into InvestmentOpportunityToVC (VCID, OppID) values (38, 11);
insert into InvestmentOpportunityToVC (VCID, OppID) values (18, 20);
insert into InvestmentOpportunityToVC (VCID, OppID) values (59, 72);
insert into InvestmentOpportunityToVC (VCID, OppID) values (22, 73);
insert into InvestmentOpportunityToVC (VCID, OppID) values (28, 76);
insert into InvestmentOpportunityToVC (VCID, OppID) values (69, 7 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (77, 28);
insert into InvestmentOpportunityToVC (VCID, OppID) values (52, 34);
insert into InvestmentOpportunityToVC (VCID, OppID) values (70, 39);
insert into InvestmentOpportunityToVC (VCID, OppID) values (26, 66);
insert into InvestmentOpportunityToVC (VCID, OppID) values (55, 13);
insert into InvestmentOpportunityToVC (VCID, OppID) values (43, 74);
insert into InvestmentOpportunityToVC (VCID, OppID) values (67, 58);
insert into InvestmentOpportunityToVC (VCID, OppID) values (39, 40);
insert into InvestmentOpportunityToVC (VCID, OppID) values (56, 77);
insert into InvestmentOpportunityToVC (VCID, OppID) values (4 , 10);
insert into InvestmentOpportunityToVC (VCID, OppID) values (78, 16);
insert into InvestmentOpportunityToVC (VCID, OppID) values (61, 42);
insert into InvestmentOpportunityToVC (VCID, OppID) values (63, 6 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (80, 3 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (64, 17);
insert into InvestmentOpportunityToVC (VCID, OppID) values (1 , 24);
insert into InvestmentOpportunityToVC (VCID, OppID) values (3 , 53);
insert into InvestmentOpportunityToVC (VCID, OppID) values (36, 69);
insert into InvestmentOpportunityToVC (VCID, OppID) values (17, 57);
insert into InvestmentOpportunityToVC (VCID, OppID) values (15, 12);
insert into InvestmentOpportunityToVC (VCID, OppID) values (57, 37);
insert into InvestmentOpportunityToVC (VCID, OppID) values (11, 30);
insert into InvestmentOpportunityToVC (VCID, OppID) values (30, 50);
insert into InvestmentOpportunityToVC (VCID, OppID) values (49, 36);
insert into InvestmentOpportunityToVC (VCID, OppID) values (65, 41);
insert into InvestmentOpportunityToVC (VCID, OppID) values (62, 64);
insert into InvestmentOpportunityToVC (VCID, OppID) values (44, 20);
insert into InvestmentOpportunityToVC (VCID, OppID) values (10, 73);
insert into InvestmentOpportunityToVC (VCID, OppID) values (38, 23);
insert into InvestmentOpportunityToVC (VCID, OppID) values (18, 14);
insert into InvestmentOpportunityToVC (VCID, OppID) values (7 , 56);
insert into InvestmentOpportunityToVC (VCID, OppID) values (13, 65);
insert into InvestmentOpportunityToVC (VCID, OppID) values (58, 33);
insert into InvestmentOpportunityToVC (VCID, OppID) values (32, 44);
insert into InvestmentOpportunityToVC (VCID, OppID) values (8 , 15);
insert into InvestmentOpportunityToVC (VCID, OppID) values (74, 49);
insert into InvestmentOpportunityToVC (VCID, OppID) values (29, 52);
insert into InvestmentOpportunityToVC (VCID, OppID) values (46, 62);
insert into InvestmentOpportunityToVC (VCID, OppID) values (68, 21);
insert into InvestmentOpportunityToVC (VCID, OppID) values (66, 68);
insert into InvestmentOpportunityToVC (VCID, OppID) values (60, 9 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (48, 26);
insert into InvestmentOpportunityToVC (VCID, OppID) values (35, 8 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (42, 48);
insert into InvestmentOpportunityToVC (VCID, OppID) values (21, 1 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (40, 72);
insert into InvestmentOpportunityToVC (VCID, OppID) values (72, 35);
insert into InvestmentOpportunityToVC (VCID, OppID) values (53, 47);
insert into InvestmentOpportunityToVC (VCID, OppID) values (41, 54);
insert into InvestmentOpportunityToVC (VCID, OppID) values (5 , 2 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (25, 60);
insert into InvestmentOpportunityToVC (VCID, OppID) values (79, 75);
insert into InvestmentOpportunityToVC (VCID, OppID) values (76, 71);
insert into InvestmentOpportunityToVC (VCID, OppID) values (12, 31);
insert into InvestmentOpportunityToVC (VCID, OppID) values (50, 32);
insert into InvestmentOpportunityToVC (VCID, OppID) values (14, 46);
insert into InvestmentOpportunityToVC (VCID, OppID) values (9 , 67);
insert into InvestmentOpportunityToVC (VCID, OppID) values (59, 27);
insert into InvestmentOpportunityToVC (VCID, OppID) values (6 , 79);
insert into InvestmentOpportunityToVC (VCID, OppID) values (54, 43);
insert into InvestmentOpportunityToVC (VCID, OppID) values (47, 61);
insert into InvestmentOpportunityToVC (VCID, OppID) values (34, 78);
insert into InvestmentOpportunityToVC (VCID, OppID) values (2 , 29);
insert into InvestmentOpportunityToVC (VCID, OppID) values (20, 63);
insert into InvestmentOpportunityToVC (VCID, OppID) values (22, 59);
insert into InvestmentOpportunityToVC (VCID, OppID) values (31, 45);
insert into InvestmentOpportunityToVC (VCID, OppID) values (23, 5 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (73, 4 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (19, 22);
insert into InvestmentOpportunityToVC (VCID, OppID) values (33, 70);
insert into InvestmentOpportunityToVC (VCID, OppID) values (27, 19);
insert into InvestmentOpportunityToVC (VCID, OppID) values (75, 38);
insert into InvestmentOpportunityToVC (VCID, OppID) values (24, 11);
insert into InvestmentOpportunityToVC (VCID, OppID) values (51, 51);
insert into InvestmentOpportunityToVC (VCID, OppID) values (16, 25);
insert into InvestmentOpportunityToVC (VCID, OppID) values (45, 55);
insert into InvestmentOpportunityToVC (VCID, OppID) values (71, 18);
insert into InvestmentOpportunityToVC (VCID, OppID) values (10, 80);
insert into InvestmentOpportunityToVC (VCID, OppID) values (49, 38);
insert into InvestmentOpportunityToVC (VCID, OppID) values (39, 73);
insert into InvestmentOpportunityToVC (VCID, OppID) values (54, 18);
insert into InvestmentOpportunityToVC (VCID, OppID) values (64, 58);
insert into InvestmentOpportunityToVC (VCID, OppID) values (41, 79);
insert into InvestmentOpportunityToVC (VCID, OppID) values (13, 26);
insert into InvestmentOpportunityToVC (VCID, OppID) values (22, 21);
insert into InvestmentOpportunityToVC (VCID, OppID) values (63, 10);
insert into InvestmentOpportunityToVC (VCID, OppID) values (69, 78);
insert into InvestmentOpportunityToVC (VCID, OppID) values (33, 48);
insert into InvestmentOpportunityToVC (VCID, OppID) values (9 , 52);
insert into InvestmentOpportunityToVC (VCID, OppID) values (47, 33);
insert into InvestmentOpportunityToVC (VCID, OppID) values (71','3);
insert into InvestmentOpportunityToVC (VCID, OppID) values (12, 49);
insert into InvestmentOpportunityToVC (VCID, OppID) values (52, 72);
insert into InvestmentOpportunityToVC (VCID, OppID) values (19, 67);
insert into InvestmentOpportunityToVC (VCID, OppID) values (27, 47);
insert into InvestmentOpportunityToVC (VCID, OppID) values (55, 50);
insert into InvestmentOpportunityToVC (VCID, OppID) values (16, 12);
insert into InvestmentOpportunityToVC (VCID, OppID) values (67, 13);
insert into InvestmentOpportunityToVC (VCID, OppID) values (70, 22);
insert into InvestmentOpportunityToVC (VCID, OppID) values (23, 2 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (50, 4 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (14, 8 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (18, 60);
insert into InvestmentOpportunityToVC (VCID, OppID) values (4 , 66);
insert into InvestmentOpportunityToVC (VCID, OppID) values (68, 15);
insert into InvestmentOpportunityToVC (VCID, OppID) values (20, 43);
insert into InvestmentOpportunityToVC (VCID, OppID) values (8 , 9 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (56, 35);
insert into InvestmentOpportunityToVC (VCID, OppID) values (40, 54);
insert into InvestmentOpportunityToVC (VCID, OppID) values (7 , 51);
insert into InvestmentOpportunityToVC (VCID, OppID) values (46, 62);
insert into InvestmentOpportunityToVC (VCID, OppID) values (59, 17);
insert into InvestmentOpportunityToVC (VCID, OppID) values (62, 74);
insert into InvestmentOpportunityToVC (VCID, OppID) values (74, 6 );
insert into InvestmentOpportunityToVC (VCID, OppID) values (1 , 32);
insert into InvestmentOpportunityToVC (VCID, OppID) values (35, 76);
insert into InvestmentOpportunityToVC (VCID, OppID) values (15, 80);
insert into InvestmentOpportunityToVC (VCID, OppID) values (25, 40);
