insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (1, 75, 'Seed', 'Technology', 'Bins-Kemmer', 'Unión');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (2, 8, 'Pre-seed', 'Healthcare', 'Willms and Sons', 'Dalai');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (3, null, 'SeriesB', 'Retail', 'Simonis-Murphy', 'Takahagi');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (4, 67, 'SeriesC', 'Education', 'Bechtelar-Ratke', 'Olho Marinho');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (5, null, 'SeriesA', 'Finance', 'Douglas-Emmerich', 'Pasirpanjang');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (6, null, 'Pre-seed', 'Healthcare', 'Bashirian-Hodkiewicz', 'Maigo');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (7, null, 'SeriesA', 'Education', 'Kuphal, Haley and Thompson', 'Rueil-Malmaison');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (8, null, 'Seed', 'Retail', 'Mitchell-Skiles', 'Tianjiaba');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (9, null, 'SeriesC', 'Finance', 'Schumm, West and Hudson', 'Diamantina');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (10, null, 'SeriesB', 'Technology', 'West, Blick and Kuhlman', 'Little Rock');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (11, null, 'SeriesB', 'Technology', 'Funk, Renner and Kassulke', 'Ban Dung');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (12, 15, 'SeriesA', 'Finance', 'Dibbert and Sons', 'Banjar Bias');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (13, null, 'Seed', 'Retail', 'Kirlin-Skiles', 'London');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (14, null, 'Pre-seed', 'Healthcare', 'Vandervort-Bailey', 'Oslo');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (15, null, 'SeriesC', 'Education', 'Wilderman Group', 'Puro');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (16, 7, 'Seed', 'Education', 'Little-Rath', 'Yuyapichis');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (17, null, 'Pre-seed', 'Finance', 'Hilll LLC', 'Xin’e');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (18, null, 'SeriesC', 'Healthcare', 'VonRueden, Rogahn and Hansen', 'Moravský Krumlov');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (19, 59, 'SeriesB', 'Technology', 'Hodkiewicz, Ferry and Runolfsson', 'Anta');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (20, null, 'SeriesA', 'Retail', 'Wiegand-Klein', 'Santiago de María');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (21, null, 'SeriesB', 'Healthcare', 'Hauck-Trantow', 'Nora');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (22, 52, 'Seed', 'Finance', 'Beer, Nienow and Heller', 'Massawa');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (23, null, 'SeriesC', 'Education', 'Kutch Group', 'Seia');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (24, null, 'Pre-seed', 'Technology', 'Stroman, Kemmer and Leffler', 'Laban');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (25, null, 'SeriesA', 'Retail', 'Gislason LLC', 'Banjiang');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (26, 17, 'SeriesC', 'Technology', 'Keebler and Sons', 'Karangranjong');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (27, 69, 'SeriesA', 'Finance', 'Haag-DuBuque', 'Oelaba');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (28, null, 'SeriesB', 'Healthcare', 'Shanahan Inc', 'Ceper');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (29, 62, 'Seed', 'Education', 'Gusikowski-Block', 'La Guata');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (30, null, 'Pre-seed', 'Retail', 'Emard-Gerhold', 'Arendal');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (31, null, 'Seed', 'Healthcare', 'Dickinson-Runolfsson', 'Richibucto');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (32, null, 'SeriesC', 'Finance', 'Prosacco, Walter and Hegmann', 'Lisewo Malborskie');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (33, null, 'SeriesB', 'Technology', 'Farrell, Casper and Roob', 'Ntobo');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (34, null, 'SeriesA', 'Education', 'Blanda-Gutkowski', 'Gongli');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (35, null, 'Pre-seed', 'Retail', 'Bernier LLC', 'Kōriyama');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (36, null, 'Pre-seed', 'Retail', 'Macejkovic-Bayer', 'Baisha');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (37, null, 'SeriesC', 'Finance', 'Klocko-Bergstrom', 'Bijelo Polje');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (38, null, 'SeriesA', 'Healthcare', 'Koelpin-Kuhic', 'Wonosari');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (39, null, 'SeriesB', 'Education', 'Schuster-O''Hara', 'Al Kittah');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (40, null, 'Seed', 'Technology', 'Jacobson Inc', 'Zhireken');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (41, null, 'SeriesA', 'Healthcare', 'Powlowski LLC', 'Vilar do Pinheiro');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (42, null, 'SeriesC', 'Finance', 'Emard-Boyle', 'Aral');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (43, null, 'SeriesB', 'Retail', 'Buckridge and Sons', 'Basa');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (44, null, 'Pre-seed', 'Education', 'Kuhlman, Pollich and Mueller', 'Muarasiau');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (45, null, 'Seed', 'Technology', 'Bednar-Kassulke', 'Sanrao');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (46, null, 'SeriesB', 'Retail', 'Koch and Sons', 'Agios Dimitrios');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (47, 41, 'Seed', 'Education', 'Erdman Group', 'Huaishu');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (48, null, 'Pre-seed', 'Technology', 'Fritsch, Larkin and Cassin', 'Kolonnawa');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (49, null, 'SeriesA', 'Healthcare', 'Adams, Hyatt and Stehr', 'Jianggao');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (50, null, 'SeriesC', 'Finance', 'Quitzon-Aufderhar', 'Torbeck');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (51, null, 'SeriesB', 'Technology', 'Quitzon-Sporer', 'Codrington');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (52, 31, 'Seed', 'Healthcare', 'Schulist and Sons', 'Pittsburgh');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (53, null, 'SeriesC', 'Finance', 'Monahan LLC', 'Huangbu');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (54, null, 'SeriesA', 'Education', 'Pfeffer Group', 'Kandangsapi');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (55, null, 'Pre-seed', 'Retail', 'Ruecker-Wyman', 'Port Colborne');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (56, 13, 'Seed', 'Retail', 'Champlin, Rice and Zulauf', 'Xiadahe');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (57, 68, 'SeriesC', 'Healthcare', 'Johnston, Leannon and Bergnaum', 'Torkanivka');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (58, null, 'Pre-seed', 'Education', 'McDermott, Wolff and Murphy', 'Agnibilékrou');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (59, null, 'SeriesA', 'Finance', 'Paucek-VonRueden', 'Piippola');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (60, null, 'SeriesB', 'Technology', 'O''Connell-Turner', 'Yuta');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (61, null, 'Seed', 'Technology', 'Fahey-Kuphal', 'Lusambo');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (62, 65, 'SeriesB', 'Healthcare', 'Barton, Russel and Aufderhar', 'Vista Alegre');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (63, null, 'SeriesA', 'Education', 'Williamson, Hudson and Rohan', 'Shouxihu');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (64, null, 'Pre-seed', 'Finance', 'Doyle and Sons', 'San Pedro');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (65, 26, 'SeriesC', 'Retail', 'Morissette, Hahn and Bergnaum', 'Polańczyk');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (66, null, 'SeriesC', 'Education', 'Oberbrunner LLC', 'Sydney Mines');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (67, null, 'SeriesA', 'Finance', 'Lesch-Prosacco', 'Kebon Tengah');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (68, null, 'Seed', 'Healthcare', 'Crist and Sons', 'Miskolc');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (69, null, 'SeriesB', 'Retail', 'Luettgen, Bergnaum and Fay', 'Cigaras');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (70, null, 'Pre-seed', 'Technology', 'Gleason LLC', 'Panchagarh');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (71, 11, 'SeriesA', 'Technology', 'Konopelski, Mann and Deckow', 'Margoyoso');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (72, null, 'SeriesB', 'Healthcare', 'Johnson, Hyatt and Zemlak', 'Cipaku');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (73, 79, 'Pre-seed', 'Finance', 'Okuneva and Sons', 'Leran Wetan');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (74, null, 'SeriesC', 'Retail', 'Hagenes, Langosh and Sauer', 'Umbanyar');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (75, null, 'Seed', 'Education', 'Kris-Ryan', 'Venilale');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (76, null, 'SeriesB', 'Education', 'Rath-Hermann', 'Kunów');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (77, null, 'SeriesC', 'Finance', 'Wolff-Jones', 'Gingsir');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (78, null, 'SeriesA', 'Technology', 'Wisoky, Heller and Zemlak', 'Shchigry');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (79, 1, 'Pre-seed', 'Retail', 'Pfeffer and Sons', 'Verdizela');
insert into Startup (StartupID, acqID, GrowthStage, Industry, Name, City) values (80, 23, 'Seed', 'Healthcare', 'D''Amore-Gerlach', 'Mazha');