insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (1, 45, 'Clio Macieja', '(194) 9123285', 'cmacieja0@scientificamerican.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (2, 32, 'Hulda Barnewell', '(578) 9399090', 'hbarnewell1@g.co');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (3, 51, 'Kerk Kittle', '(124) 2394291', 'kkittle2@wix.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (4, 39, 'Gayle Shernock', '(659) 4593080', 'gshernock3@eventbrite.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (5, 62, 'Wit Luckhurst', '(653) 1669982', 'wluckhurst4@de.vu');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (6, 46, 'Davis Baynom', '(838) 1100033', 'dbaynom5@51.la');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (7, 23, 'Kimbell Dering', '(637) 5834165', 'kdering6@lulu.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (8, 63, 'Wallis Whysall', '(936) 9172059', 'wwhysall7@histats.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (9, 1 , 'Gates Devenport', '(102) 3600730', 'gdevenport8@list-manage.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (10, 37, 'Glenden McLarty', '(369) 5575880', 'gmclarty9@w3.org');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (11, 80, 'Clareta Bamford', '(855) 5671406', 'cbamforda@cbsnews.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (12, 66, 'Alexei Bigham', '(848) 9474292', 'abighamb@fc2.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (13, 53, 'Doreen Mongenot', '(339) 8451024', 'dmongenotc@naver.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (14, 28, 'Giacobo Trevino', '(671) 7957868', 'gtrevinod@yelp.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (15, 16, 'Bevan Scutching', '(817) 6772834', 'bscutchinge@japanpost.jp');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (16, 77, 'Chelsae Cromly', '(938) 4672611', 'ccromlyf@meetup.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (17, 31, 'Kellen Midgely', '(338) 2949988', 'kmidgelyg@sbwire.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (18, 64, 'Merissa MacPadene', '(897) 2813006', 'mmacpadeneh@opensource.org');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (19, 18, 'Abey Othen', '(235) 5064785', 'aotheni@biglobe.ne.jp');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (20, 17, 'Chad Booker', '(534) 8242772', 'cbookerj@shop-pro.jp');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (21, 47, 'Genovera Burras', '(606) 7037214', 'gburrask@imageshack.us');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (22, 14, 'Shelli Sollam', '(518) 8426755', 'ssollaml@sitemeter.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (23, 4 , 'Hector Geindre', '(554) 1724634', 'hgeindrem@berkeley.edu');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (24, 20, 'Isaak Gabriely', '(646) 1990026', 'igabrielyn@cbslocal.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (25, 6 , 'Etty Kirkwood', '(613) 5736402', 'ekirkwoodo@rambler.ru');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (26, 69, 'Bee Vasyunkin', '(703) 1637129', 'bvasyunkinp@arstechnica.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (27, 3 , 'Rebecka Pettet', '(733) 6016201', 'rpettetq@oakley.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (28, 13, 'Tallie Ramble', '(688) 6825372', 'trambler@weibo.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (29, 40, 'Anita Gunter', '(363) 5465469', 'agunters@com.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (30, 73, 'Steffen Patis', '(710) 5527051', 'spatist@theguardian.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (31, 65, 'Germain Mourge', '(448) 7972335', 'gmourgeu@naver.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (32, 72, 'Silva Keir', '(674) 4037114', 'skeirv@imgur.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (33, 70, 'Dulcea Lugton', '(195) 7456700', 'dlugtonw@ask.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (34, 24, 'Elinor Culpen', '(418) 7283271', 'eculpenx@sourceforge.net');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (35, 54, 'Jewell Swendell', '(169) 4574323', 'jswendelly@people.com.cn');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (36, 44, 'Christalle Wyett', '(790) 7022696', 'cwyettz@berkeley.edu');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (37, 43, 'Fanni Butland', '(984) 4734422', 'fbutland10@sciencedirect.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (38, 76, 'Mellisent Griggs', '(407) 2625669', 'mgriggs11@techcrunch.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (39, 68, 'Deana Marusik', '(892) 5345997', 'dmarusik12@dailymail.co.uk');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (40, 71, 'Sydel Brackley', '(835) 6283979', 'sbrackley13@mit.edu');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (41, 75, 'Laure Fisk', '(720) 8702332', 'lfisk14@senate.gov');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (42, 35, 'Whitney Cansdale', '(809) 8902848', 'wcansdale15@comcast.net');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (43, 12, 'Guglielma Gowen', '(412) 3366194', 'ggowen16@yolasite.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (44, 30, 'Shelagh Vipan', '(404) 1076675', 'svipan17@arstechnica.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (45, 34, 'Brandy Wood', '(576) 3455057', 'bwood18@nasa.gov');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (46, 8 , 'Helene Sinnett', '(461) 8386779', 'hsinnett19@surveymonkey.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (47, 7 , 'Kylynn Clementel', '(531) 3893528', 'kclementel1a@bbb.org');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (48, 19, 'Rik Petrov', '(282) 1122048', 'rpetrov1b@slate.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (49, 67, 'Averill Livingstone', '(762) 2315546', 'alivingstone1c@biglobe.ne.jp');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (50, 52, 'Lanie Horsfield', '(118) 6664272', 'lhorsfield1d@theguardian.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (51, 29, 'Eustace Gilston', '(695) 1691593', 'egilston1e@printfriendly.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (52, 42, 'Georg Buckoke', '(111) 1573795', 'gbuckoke1f@ftc.gov');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (53, 9 , 'Frederik Gopsell', '(106) 6752227', 'fgopsell1g@1und1.de');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (54, 60, 'Northrup Colten', '(602) 6732289', 'ncolten1h@ca.gov');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (55, 61, 'Lizette Whitters', '(200) 3412223', 'lwhitters1i@msu.edu');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (56, 11, 'Bonny Clew', '(200) 1683275', 'bclew1j@a8.net');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (57, 33, 'Merissa Bohea', '(590) 1154418', 'mbohea1k@disqus.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (58, 10, 'Guntar Elves', '(645) 2194723', 'gelves1l@trellian.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (59, 41, 'Emlyn Clarricoates', '(863) 4929801', 'eclarricoates1m@abc.net.au');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (60, 78, 'Deane Werendell', '(311) 9683189', 'dwerendell1n@indiegogo.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (61, 57, 'Iorgo Swatheridge', '(857) 7240387', 'iswatheridge1o@census.gov');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (62, 58, 'Janot Glencrosche', '(101) 2287841', 'jglencrosche1p@usgs.gov');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (63, 27, 'Garnet Oxbrow', '(149) 8896222', 'goxbrow1q@merriam-webster.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (64, 36, 'Miguela Crippen', '(247) 2405979', 'mcrippen1r@globo.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (65, 21, 'Bary Vlasyuk', '(200) 1808488', 'bvlasyuk1s@boston.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (66, 2 , 'Thelma Skillington', '(901) 9071104', 'tskillington1t@delicious.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (67, 48, 'Eimile Hitchens', '(465) 7239899', 'ehitchens1u@gmpg.org');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (68, 49, 'Neilla Orry', '(321) 3842718', 'norry1v@irs.gov');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (69, 5 , 'Windy Spours', '(626) 9360008', 'wspours1w@wix.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (70, 74, 'Dar Quincey', '(221) 8408578', 'dquincey1x@wordpress.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (71, 56, 'Almire Robben', '(763) 7014851', 'arobben1y@godaddy.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (72, 38, 'Davy Curnnokk', '(871) 4233737', 'dcurnnokk1z@oracle.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (73, 79, 'Stewart Denekamp', '(746) 6948786', 'sdenekamp20@mapquest.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (74, 22, 'Lennie Govern', '(627) 2810207', 'lgovern21@google.co.uk');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (75, 15, 'Yank Coundley', '(186) 8060530', 'ycoundley22@hexun.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (76, 26, 'Delora Murrill', '(614) 4418106', 'dmurrill23@purevolume.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (77, 59, 'Sari Gillatt', '(960) 1297065', 'sgillatt24@google.fr');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (78, 50, 'Ryley Franc', '(164) 9426961', 'rfranc25@java.com');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (79, 25, 'Lurlene Nisbet', '(136) 2414768', 'lnisbet26@jalbum.net');
insert into TeamMembers (MemberID, StartupID, Name, PhoneNumber, Email) values (80, 80, 'Abdul Burhill', '(669) 5068052', 'aburhill27@howstuffworks.com');