insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (1, 'Marks, Lueilwitz and Franecki', 'Technology', 93);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (2, 'Hilll-Witting', 'Healthcare', 84);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (3, 'Weimann and Sons', 'Education', 16);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (4, 'Lynch LLC', 'Education', 93);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (5, 'Hudson, Gibson and Goyette', 'Retail', 8);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (6, 'Boyle, Schoen and Bernhard', 'Education', 95);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (7, 'Rohan and Sons', 'Healthcare', 90);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (8, 'Murray-Stanton', 'Finance', 29);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (9, 'Jacobs Inc', 'Finance', 87);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (10, 'Kovacek LLC', 'Retail', 52);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (11, 'Zboncak-Halvorson', 'Healthcare', 67);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (12, 'Davis Group', 'Education', 87);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (13, 'Sawayn, Graham and Parker', 'Technology', 66);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (14, 'Shanahan-Baumbach', 'Healthcare', 2);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (15, 'Littel-Labadie', 'Retail', 80);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (16, 'Sporer-Stoltenberg', 'Technology', 25);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (17, 'McGlynn and Sons', 'Retail', 14);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (18, 'Wehner Group', 'Retail', 93);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (19, 'Wolf and Sons', 'Finance', 97);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (20, 'Corkery Inc', 'Healthcare', 10);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (21, 'Homenick-Pagac', 'Retail', 20);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (22, 'Ondricka, Kessler and Swaniawski', 'Healthcare', 38);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (23, 'Stokes, Bruen and Harris', 'Education', 16);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (24, 'Murray LLC', 'Education', 76);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (25, 'Jenkins Group', 'Retail', 87);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (26, 'Wisozk, Hettinger and Rowe', 'Finance', 77);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (27, 'Gerlach and Sons', 'Healthcare', 31);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (28, 'Ferry-Brown', 'Technology', 2);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (29, 'Nader Group', 'Healthcare', 26);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (30, 'Watsica-Corwin', 'Healthcare', 69);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (31, 'Mann Group', 'Retail', 18);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (32, 'Cormier-Schroeder', 'Technology', 42);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (33, 'Bauch and Sons', 'Healthcare', 67);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (34, 'Bernier, Walter and Armstrong', 'Finance', 79);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (35, 'Runolfsson Group', 'Healthcare', 1);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (36, 'Mosciski-Morissette', 'Retail', 96);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (37, 'Hoeger, Schneider and Homenick', 'Education', 98);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (38, 'Kihn LLC', 'Education', 71);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (39, 'Schamberger, Weimann and Beatty', 'Technology', 19);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (40, 'Barton, Lockman and Toy', 'Retail', 81);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (41, 'Cole-Barton', 'Technology', 47);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (42, 'Kutch and Sons', 'Finance', 35);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (43, 'Auer Group', 'Technology', 59);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (44, 'Wehner LLC', 'Technology', 66);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (45, 'Davis-Ullrich', 'Technology', 20);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (46, 'Bode Group', 'Education', 62);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (47, 'Ortiz, Rohan and Franecki', 'Technology', 46);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (48, 'Wyman-Murazik', 'Retail', 41);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (49, 'Kris-McGlynn', 'Technology', 19);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (50, 'Keeling-Feil', 'Healthcare', 23);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (51, 'Torphy and Sons', 'Technology', 10);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (52, 'Hahn and Sons', 'Education', 66);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (53, 'Schneider and Sons', 'Education', 65);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (54, 'Greenholt, Barrows and Moen', 'Retail', 19);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (55, 'Buckridge, O''Kon and Sawayn', 'Healthcare', 4);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (56, 'Lueilwitz-Jaskolski', 'Healthcare', 9);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (57, 'Buckridge and Sons', 'Education', 64);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (58, 'Marquardt-Welch', 'Technology', 72);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (59, 'Hegmann Inc', 'Technology', 33);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (60, 'O''Connell Inc', 'Education', 76);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (61, 'Greenfelder Group', 'Technology', 87);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (62, 'Becker-Bergnaum', 'Technology', 20);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (63, 'Christiansen Inc', 'Finance', 88);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (64, 'Reichel, Crooks and Kohler', 'Finance', 59);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (65, 'Jakubowski, Kessler and Smith', 'Finance', 58);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (66, 'Jacobi Inc', 'Technology', 94);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (67, 'Bernier-Cormier', 'Retail', 77);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (68, 'Lubowitz, Krajcik and Kessler', 'Retail', 95);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (69, 'Beahan-Toy', 'Technology', 24);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (70, 'Wilderman Inc', 'Technology', 74);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (71, 'Jacobson, Bashirian and Bogan', 'Technology', 25);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (72, 'Funk LLC', 'Education', 44);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (73, 'Bergstrom and Sons', 'Technology', 69);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (74, 'Crooks LLC', 'Technology', 39);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (75, 'Ledner-Reynolds', 'Healthcare', 77);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (76, 'Luettgen, Legros and Schmidt', 'Healthcare', 15);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (77, 'Gutmann, Marquardt and Aufderhar', 'Finance', 77);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (78, 'Aufderhar, Strosin and Berge', 'Technology', 11);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (79, 'Langosh LLC', 'Finance', 80);
insert into VentureCapitalist (VCID, Name, Industry_Preference, PortfolioSize) values (80, 'Schulist-Armstrong', 'Healthcare', 80);